SELECT c.SUBSCRIBER_CATEGORY_NAME  AS SUBSCRIBER_CATEGORY,COALESCE (e.CALL_TYPE_NAME,TO_CHAR(a.CALL_TYPE) ) AS CALL_TYPE 
,d.MEDIA_TYPE_NAME AS MEDIA_TYPE,b.SERVICE_KEY,ROUND(a.GRANTED_QUOTA/60) AS GRANTED_IN_MINUTE ,a.DESCRIPTION 
FROM SCPUSER.BFT_RULES_MASTER a
LEFT JOIN SCPUSER.BFT_SERVICE_LIST b ON a.SUBSCRIBER_TYPE=b.SERVICEID 
LEFT JOIN SCPUSER.SUBSCRIBER_CATEGORY c ON a.SUBSCRIBER_CATEGORY=c.SUBSCRIBER_CATEGORY_ID 
LEFT JOIN SCPUSER.MEDIA_TYPE d ON a.MEDIA_TYPE=d.MEDIA_TYPE_ID 
LEFT JOIN SCPUSER.CALL_TYPE_MASTER e ON a.CALL_TYPE =e.CALL_TYPE_ID 
ORDER BY c.SUBSCRIBER_CATEGORY_NAME