WITH base_statistic AS (SELECT DECODE(IS_ROAMING,1,'ROAMING',0,'NOT ROAMING') AS ROAMING_STATUS,SERVICE_KEY
 ,COUNT(TRANSACTION_ID) AS CALL_ATTEMPT
 ,SUM(CASE WHEN DIAMETER_RESULT_CODES='2001' THEN 1 ELSE 0 END) AS SUCC
 ,SUM(CASE WHEN DIAMETER_RESULT_CODES='5030' THEN 1 ELSE 0 END) AS BLCK
 ,SUM(CASE WHEN DIAMETER_RESULT_CODES='5031' THEN 1 ELSE 0 END) AS UNKS
 ,SUM(CASE WHEN DIAMETER_RESULT_CODES='4010' THEN 1 ELSE 0 END) AS SUSP
 ,SUM(CASE WHEN DIAMETER_RESULT_CODES='4012' THEN 1 ELSE 0 END) AS INSF
 ,SUM(CASE WHEN DIAMETER_RESULT_CODES NOT IN ('2001','5030','5031','4010','4012') OR DIAMETER_RESULT_CODES IS NULL  THEN 1 ELSE 0 END) AS FAIL
FROM SCPCDR.INTERNAL_CDR_{day}
WHERE M_MONTH ='{mon}' 
GROUP BY DECODE(IS_ROAMING,1,'ROAMING',0,'NOT ROAMING'),SERVICE_KEY )
SELECT ROAMING_STATUS,SERVICE_KEY,CALL_ATTEMPT,SUCC,BLCK,UNKS,SUSP,INSF,FAIL
   ,ROUND((SUCC/CALL_ATTEMPT)*100,2) AS SUCCESS_RATE
   ,ROUND((BLCK/CALL_ATTEMPT)*100,2) AS BLOCK_RATE
   ,ROUND((UNKS/CALL_ATTEMPT)*100,2) AS UNKS_RATE
   ,ROUND((SUSP/CALL_ATTEMPT)*100,2) AS SUSPEND_RATE
   ,ROUND((INSF/CALL_ATTEMPT)*100,2) AS INSF_RATE
   ,ROUND((FAIL/CALL_ATTEMPT)*100,2) AS FAILED_RATE
FROM base_statistic
ORDER BY ROAMING_STATUS,SERVICE_KEY