WITH base_d0 AS (SELECT to_char(CDR_TIMESTAMP,'dd-mm-yyyy') AS cdr_date
,COUNT(TRANSACTION_ID) AS attempt
,SUM(CASE WHEN DIAMETER_RESULT_CODES='2001' THEN 1 ELSE 0 END) AS succ
,SUM(CASE WHEN DIAMETER_RESULT_CODES IN ('5030','5031','4010','4012') THEN 1 ELSE 0 END) AS bsfail
,SUM(CASE WHEN DIAMETER_RESULT_CODES NOT IN ('2001','5030','5031','4010','4012') OR DIAMETER_RESULT_CODES IS NULL  THEN 1 ELSE 0 END) AS FAIL    
FROM SCPCDR.INTERNAL_CDR_{day0}
WHERE M_MONTH ='{mon0}' 
GROUP BY to_char(CDR_TIMESTAMP,'dd-mm-yyyy')
UNION
SELECT to_char(CDR_TIMESTAMP,'dd-mm-yyyy') AS cdr_date
,COUNT(TRANSACTION_ID) AS attempt
,SUM(CASE WHEN DIAMETER_RESULT_CODES='2001' THEN 1 ELSE 0 END) AS succ
,SUM(CASE WHEN DIAMETER_RESULT_CODES IN ('5030','5031','4010','4012') THEN 1 ELSE 0 END) AS bsfail
,SUM(CASE WHEN DIAMETER_RESULT_CODES NOT IN ('2001','5030','5031','4010','4012') OR DIAMETER_RESULT_CODES IS NULL  THEN 1 ELSE 0 END) AS FAIL    
FROM SCPCDR.INTERNAL_CDR_{day0}@scpcdr_prod_pk_public
WHERE M_MONTH ='{mon0}'  
GROUP BY to_char(CDR_TIMESTAMP,'dd-mm-yyyy') ),
base_d1 AS (SELECT to_char(CDR_TIMESTAMP,'dd-mm-yyyy') AS cdr_date
,COUNT(TRANSACTION_ID) AS attempt
,SUM(CASE WHEN DIAMETER_RESULT_CODES='2001' THEN 1 ELSE 0 END) AS succ
,SUM(CASE WHEN DIAMETER_RESULT_CODES IN ('5030','5031','4010','4012') THEN 1 ELSE 0 END) AS bsfail
,SUM(CASE WHEN DIAMETER_RESULT_CODES NOT IN ('2001','5030','5031','4010','4012') OR DIAMETER_RESULT_CODES IS NULL  THEN 1 ELSE 0 END) AS FAIL    
FROM SCPCDR.INTERNAL_CDR_{day1}
WHERE M_MONTH ='{mon1}' AND to_char(CDR_TIMESTAMP,'HH24') <= to_char(SYSDATE,'HH24')
GROUP BY to_char(CDR_TIMESTAMP,'dd-mm-yyyy')
UNION
SELECT to_char(CDR_TIMESTAMP,'dd-mm-yyyy') AS cdr_date
,COUNT(TRANSACTION_ID) AS attempt
,SUM(CASE WHEN DIAMETER_RESULT_CODES='2001' THEN 1 ELSE 0 END) AS succ
,SUM(CASE WHEN DIAMETER_RESULT_CODES IN ('5030','5031','4010','4012') THEN 1 ELSE 0 END) AS bsfail
,SUM(CASE WHEN DIAMETER_RESULT_CODES NOT IN ('2001','5030','5031','4010','4012') OR DIAMETER_RESULT_CODES IS NULL  THEN 1 ELSE 0 END) AS FAIL    
FROM SCPCDR.INTERNAL_CDR_{day1}@scpcdr_prod_pk_public
WHERE M_MONTH ='{mon1}' AND to_char(CDR_TIMESTAMP,'HH24') <= to_char(SYSDATE,'HH24')
 GROUP BY to_char(CDR_TIMESTAMP,'dd-mm-yyyy') )
 SELECT cdr_date
 ,SUM(ATTEMPT) AS CALL_ATTEMPT
 ,SUM(SUCC) AS CALL_SUCCESS
 ,SUM(BSFAIL) AS CALL_BUSSFAIL
 ,SUM(FAIL) AS SYSTEM_FAIL
 FROM
(SELECT *
FROM base_d0
UNION
SELECT *
FROM base_d1)
GROUP BY cdr_date
ORDER BY cdr_date


