WITH BASE  as (SELECT b.NAME,a.CP_ID,a.CONNECTION_NAME,a.SUBSCRIPTION_TYPE  ,a.CONNECTION_TYPE ,a.SYSTEM_ID ,a.PASSWORD ,a.MAX_CONCURRENT_CONNECTION,a.TPS,a.MO_URL_1 ,a.MO_URL_2 ,a.DR_URL1 ,a.DR_URL2 ,a.STATUS 
FROM SCMUSER.SUBSCRIPTION_CP_CONNECTION a 
LEFT JOIN SCMUSER.PROVIDER_CP b ON a.CP_ID =b.CP_ID
ORDER BY a.STATUS)
SELECT *
FROM BASE 
{condition}
