SELECT a.CP_NAME,a.OFFER_CODE,a.OFFER_NAME,a.OFFER_DESC,a.OFFER_TYPE,a.SHORT_CODE,a.SUBSCRIPTION_FLOW,a.COMMIT_AT 
,a.AUTO_RENEWAL_MAX_SPAN,a.EXTERNAL_PROVISIONING_TYPE,a.SUBSCRIPTION_MODE,a.TYPE_OF_SERVICE,a.TYPE_OF_CHARGING
,a.CODE_ARGUMENT,a.STATUS 
FROM SCMUSER.SUBSCRIPTION_OFFER a
LEFT JOIN SCMUSER.PROVIDER_CP b ON a.CP_ID=b.CP_ID  
{condition}
ORDER BY a.OFFER_ID