SELECT CP_ID,CP_NAME,OFFER_CODE ,OFFER_NAME ,OFFER_DESC ,OFFER_TYPE,SUBSCRIPTION_TYPE,TYPE_OF_SERVICE ,TYPE_OF_CHARGING ,SHORT_CODE,COMMIT_AT,CODE_ARGUMENT,STATUS
FROM SCMUSER.SUBSCRIPTION_OFFER
WHERE {condition}