WITH base_statistic AS (SELECT to_char(CDR_TIMESTAMP,'dd-mm-yyyy') AS cdr_date,to_char(CDR_TIMESTAMP,'HH24') AS cdr_hour,DECODE(IS_ROAMING,1,'ROAMING',0,'NOT ROAMING') AS ROAMING_STATUS
 ,COUNT(TRANSACTION_ID) AS CALL_ATTEMPT
 ,SUM(CASE WHEN DIAMETER_RESULT_CODES='2001' THEN 1 ELSE 0 END) AS SUCC
 ,SUM(CASE WHEN DIAMETER_RESULT_CODES IN ('5030','5031','4010','4012') THEN 1 ELSE 0 END) AS BSF
 ,SUM(CASE WHEN DIAMETER_RESULT_CODES NOT IN ('2001','5030','5031','4010','4012') OR DIAMETER_RESULT_CODES IS NULL  THEN 1 ELSE 0 END) AS FAIL
FROM SCPCDR.INTERNAL_CDR_{day}
WHERE M_MONTH ='{mon}' 
GROUP BY to_char(CDR_TIMESTAMP,'dd-mm-yyyy'),to_char(CDR_TIMESTAMP,'HH24'),DECODE(IS_ROAMING,1,'ROAMING',0,'NOT ROAMING')
UNION
SELECT to_char(CDR_TIMESTAMP,'dd-mm-yyyy') AS cdr_date,to_char(CDR_TIMESTAMP,'HH24') AS cdr_hour,DECODE(IS_ROAMING,1,'ROAMING',0,'NOT ROAMING') AS ROAMING_STATUS
 ,COUNT(TRANSACTION_ID) AS CALL_ATTEMPT
 ,SUM(CASE WHEN DIAMETER_RESULT_CODES='2001' THEN 1 ELSE 0 END) AS SUCC
 ,SUM(CASE WHEN DIAMETER_RESULT_CODES in ('5030','5031','4010','4012') THEN 1 ELSE 0 END) AS BSF
 ,SUM(CASE WHEN DIAMETER_RESULT_CODES NOT IN ('2001','5030','5031','4010','4012') OR DIAMETER_RESULT_CODES IS NULL  THEN 1 ELSE 0 END) AS FAIL
FROM SCPCDR.INTERNAL_CDR_{day}@scpcdr_prod_pk_public
WHERE M_MONTH ='{mon}' 
GROUP BY to_char(CDR_TIMESTAMP,'dd-mm-yyyy'),to_char(CDR_TIMESTAMP,'HH24'),DECODE(IS_ROAMING,1,'ROAMING',0,'NOT ROAMING'))
SELECT cdr_date,cdr_hour
   ,SUM(CASE WHEN ROAMING_STATUS='NOT ROAMING' THEN CALL_ATTEMPT ELSE 0 END) AS NR_CALL_ATTEMPT
   ,SUM(CASE WHEN ROAMING_STATUS='NOT ROAMING' THEN SUCC ELSE 0 END) AS NR_CALL_SUCCESS
   ,SUM(CASE WHEN ROAMING_STATUS='NOT ROAMING' THEN BSF ELSE 0 END) AS NR_CALL_BSF
   ,SUM(CASE WHEN ROAMING_STATUS='NOT ROAMING' THEN FAIL ELSE 0 END) AS NR_CALL_FAIL
   ,SUM(CASE WHEN ROAMING_STATUS='ROAMING' THEN CALL_ATTEMPT ELSE 0 END) AS RM_CALL_ATTEMPT
   ,SUM(CASE WHEN ROAMING_STATUS='ROAMING' THEN SUCC ELSE 0 END) AS RM_CALL_SUCCESS
   ,SUM(CASE WHEN ROAMING_STATUS='ROAMING' THEN BSF ELSE 0 END) AS RM_CALL_BSF
   ,SUM(CASE WHEN ROAMING_STATUS='ROAMING' THEN FAIL ELSE 0 END) AS RM_CALL_FAIL
FROM base_statistic
GROUP BY cdr_date,cdr_hour
ORDER BY cdr_hour