WITH base AS ( SELECT to_char(CDR_TIMESTAMP,'dd-mm-yyyy HH24:MM:SS') as CDR_TIMESTAMP,CALL_REFERENCE_NUMBER,TRANSACTION_ID,CALLING_PARTY,CALLED_PARTY,SUBSCRIBER_TYPE,CALL_STATUS,DIAMETER_RESULT_CODES,DIAMETER_ERROR_MESSAGE,CELL_ID,MSC_ADDRESS,VLR_ADDRESS,DIAMTER_SESSION_ID,INSTANCE_ID,CALL_TYPE,SUB_CALL_TYPE,IS_ROAMING,IS_CHARGING_OVERRULED,ISBFT,CALL_ANSWER_TIME as CALL_START_TIME,CALL_DISCONNECTING_TIME,CALL_DURATION,NORMALISED_NUMBER,TRANSLATED_NUMBER,SERVICE_KEY,IS_FOC
FROM SCPCDR.INTERNAL_CDR_{day}
WHERE M_MONTH= '{mon}'
AND to_char(CDR_TIMESTAMP,'HH24')='{hour}'
AND CALLING_PARTY  LIKE ('%{msisdn}')
UNION ALL
SELECT to_char(CDR_TIMESTAMP,'dd-mm-yyyy HH24:MM:SS') as CDR_TIMESTAMP,CALL_REFERENCE_NUMBER,TRANSACTION_ID,CALLING_PARTY,CALLED_PARTY,SUBSCRIBER_TYPE,CALL_STATUS,DIAMETER_RESULT_CODES,DIAMETER_ERROR_MESSAGE,CELL_ID,MSC_ADDRESS,VLR_ADDRESS,DIAMTER_SESSION_ID,INSTANCE_ID,CALL_TYPE,SUB_CALL_TYPE,IS_ROAMING,IS_CHARGING_OVERRULED,ISBFT,CALL_ANSWER_TIME as CALL_START_TIME,CALL_DISCONNECTING_TIME,CALL_DURATION,NORMALISED_NUMBER,TRANSLATED_NUMBER,SERVICE_KEY,IS_FOC
FROM SCPCDR.INTERNAL_CDR_{day}@scpcdr_prod_pk_public 
WHERE M_MONTH= '{mon}'
AND to_char(CDR_TIMESTAMP,'HH24')='{hour}'
AND CALLING_PARTY  LIKE ('%{msisdn}')
)
SELECT *
FROM BASE