SELECT d.NAME,b.OFFER_NAME,c.CONNECTION_NAME,DECODE(c.CONNECTION_TYPE,'0','SMPP','1','HTTP') AS CONNECTION_TYPE
,DECODE(a.TYPE_OF_DIRECTION,'0','MT','1','MO') AS TYPE_OF_DIRECTION
,a.SENDER_MASKING_ADDRESS ,a.MO_SHORT_CODE ,a.MO_KEYWORD ,a.OPERATION_TYPE ,a.CHARGE_AMOUNT,a.STATUS
FROM SCMUSER.SUBSCRIPTION_SDC a
LEFT JOIN SCMUSER.SUBSCRIPTION_OFFER b ON a.OFFER_ID=b.OFFER_CODE 
LEFT JOIN SCMUSER.SUBSCRIPTION_CP_CONNECTION c ON a.CP_ID=c.CP_ID 
LEFT JOIN SCMUSER.PROVIDER_CP d ON a.CP_ID=d.CP_ID 
{condition}
ORDER BY a.CP_ID
