SELECT to_char(TIMESTAMP,'yyyy-mm-dd HH24:MM:SS') AS CDRTIME,TASKID ,CLIENTTRANSACTIONID,TRANSACTIONID,APARTY,BASICCAUSE,INTERNALCAUSE,CALLCHARGE
,OFFERCODE,CP_NAME,CONTENTPROVIDERID,NETWORKMODE,SHORTCODE ,KEYWORD ,CATEGORYID,THIRDPARTYERRORCODE 
FROM SCMCDR.SCM_CC_{mon}
WHERE M_DAY='{day}'AND HOUR='{hour}' and APARTY like ('%{msisdn}')
ORDER BY to_char(TIMESTAMP,'yyyy-mm-dd HH24:MM:SS')